[package]
name = "codectrl-protobuf-bindings"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.7"
futures-core = "0.3"
prost = "0.10"


[build-dependencies]
tonic-build = "0.7"
